Added nix flake for convenience
worldcoin/orb-firmware pull request #13
Opened 2024-04-17 21:43 UTC by TheButlah

2024-04-18 07:14 UTC, fouge commented on flake.nix
> +          cffi
I don't think we need these

2024-04-18 07:20 UTC, fouge requested changes
A conda environment file is available in `orb/utils/env/environment.yml`, can we move the flake files to this location as well? I know it's probably not the standard way to do it, but I don't want to bloat the root directory with files that aren't going to be used by most of the developers. 

I would accept putting this file in the root directory only if it brings everything that's needed to build the firmware, and I would love to use nix in this repo, so if you have some time, we can try to bring the full environment with nix.

2024-04-19 16:35 UTC, TheButlah commented on flake.nix
> +          cffi
they are necessary for pyocd

2024-04-19 16:37 UTC, TheButlah commented
Moved filed into `utils/env` folder. You can `cp utils/env/.envrc.example .envrc` to source the flake.

2024-04-29 05:32 UTC, fouge approved these changes

2024-04-29 16:41 UTC, merged