feat(reboot reason): reason published on mcu-util requested reboot
worldcoin/orb-firmware pull request #141
Opened 2024-12-30 04:37 UTC by sri9311

https://github.com/worldcoin/orb-messages/pull/42 needs to go in first, then dependency in `west.yml` will be updated in a follow-up commit

publish ShutdownScheduled msg w/JETSON_REQUESTED_REBOOT on mcu-util reboot

2024-12-30 17:18 UTC, TheButlah approved these changes
approving, but consider getting @fouge to take a look

2025-01-06 09:02 UTC, fouge requested changes
you need to track the new head of https://github.com/worldcoin/orb-messages/ following the merge of https://github.com/worldcoin/orb-messages/pull/42 in `west.yml`

2025-01-06 09:23 UTC, fouge reviewed
IMO we should rely on Memfault's reboot reason and depreciate that one which is far from complete unfortunately.

2025-01-07 20:21 UTC, TheButlah commented
hmm I don't know. I think I would prefer having our own reboot reason. Its our business logic so it should be our reboot reason, right?

2025-01-08 07:14 UTC, fouge commented
I added our own reboot reasons, on top of the system ones (hard faults etc)
see 
https://github.com/worldcoin/orb-firmware/blob/main/main_board/config/memfault_reboot_reason_user_config.def

2025-01-14 14:32 UTC, fouge commented
@sri9311 anything i can do to help make progress on that task?

list of things to change:
- [ ] add `JetsonRequestedShutdown` reboot reason.
- [ ] report `JetsonRequestedShutdown` from `runner.c:handle_shutdown`
- [ ] add `JetsonRequestedReboot` and `JetsonRequestedShutdown` to Memfault reboot reasons
- [ ] report `JetsonRequestedReboot` and `JetsonRequestedShutdown` events to Memfault

2025-01-14 16:30 UTC, sri9311 commented
@fouge I'll make these changes today, I was busy exploring JSON, forgot about this!

2025-01-15 10:44 UTC, fouge requested changes
I would make sure the reboot command has been successfully taken into account before sending the event and telling Memfault the reboot reason.

2025-01-15 10:44 UTC, fouge commented on main_board/src/runner/runner.c
> +#endif
we should do all of this only if `reboot()` returns `RET_SUCCESS` below. 

Otherwise, the reboot command failed and thus the event shouldn't be sent to the Jetson nor marked to Memfault.

2025-01-15 17:14 UTC, fouge approved these changes

2025-01-16 10:27 UTC, merged