version: add Mainboard B3
worldcoin/orb-firmware pull request #17
Opened 2024-04-22 09:11 UTC by moritz-diller

Add support for Mainboard hardware version 4.2 which is used in the Diamond B3 build.

fixes O-2619

2024-04-29 05:35 UTC, fouge requested changes
let's track orb-messages main branch

2024-04-29 05:35 UTC, fouge commented on west.yml
> +      revision: 61e2ad2a7567266c805bae6e3d10775eb2964db7
the PR has been merged on the orb-messages side, let's track the commit in the main branch

2024-04-29 07:43 UTC, moritz-diller commented
@fouge let's wait until we received the new boards and tested this PR, before we merge.

2024-05-06 13:06 UTC, fouge approved these changes

2024-05-06 13:08 UTC, merged

2024-05-06 13:20 UTC, fouge commented
I wanted to go a bit faster so that I can make progress on my side.
in any case this is going to be tested as soon as we have the board :)